config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  
  resources :newsletters
  devise_for :users
root 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :newsletters
  
  validates :nick_name, :first_name, :last_name, presence: true
  enum role: %i[user professional admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :first_name, :last_name])
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @newsletters = current_user.present? ? current_user.newsletters : nill
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: %i[ show edit update destroy ]

  # GET /newsletters or /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1 or /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters or /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params.merge(user: current_user))

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to newsletter_url(@newsletter), notice: "Newsletter was successfully created." }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1 or /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to newsletter_url(@newsletter), notice: "Newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1 or /newsletters/1.json
  def destroy
    @newsletter.destroy

    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: "Newsletter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newsletter_params
      params.require(:newsletter).permit(:comment, :active, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/homes/index.html.erb
<div class='container'>
<h1>Containment</h1>
<H3>No Condenamos, Nos Apoyamos</H3>
<h3>Tu Privacidad es muy importante, tus datos están protegidos</h3>
<table>
    <tbody>
        <% if @newsletters %>
            <td>Boletines:</td>
            <td><%= @newsletters.size %></td>
        <% end %>   
    </tbody>
</table>

<% if @newsletters %>

<div class="container">
    <% @newsletters.each do |newsletter| %>
    <%= render 'newsletters/newsletter', newsletter: newsletter %>
    <% end %>
</div>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Containment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/newsletters/_form.html.erb
<%= form_with(model: newsletter) do |form| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
        <% newsletter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newsletters/_newsletter.html.erb
<div class='col-sm-3'>
    <img src="<%= newsletter.url %>" width= "200" alt="">
</div>

app/views/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Comment</th>
      <th>Active</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.url %></td>
        <td><%= newsletter.comment %></td>
        <td><%= newsletter.active %></td>
        <td><%= newsletter.user_id %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1>New Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Back', newsletters_path %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @newsletter.url %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @newsletter.comment %>
</p>

<p>
  <strong>Active:</strong>
  <%= @newsletter.active %>
</p>

<p>
  <strong>User:</strong>
  <%= @newsletter.user_id %>
</p>

<%= link_to 'Edit', edit_newsletter_path(@newsletter) %> |
<%= link_to 'Back', newsletters_path %>